name: Build and release LaTeX document
on:
  workflow_dispatch: # Allows the action to be triggered manually
  push:
    branches:
      - "master"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2 
        with:
          root_file: main.tex
          post_compile: mv main.pdf template.pdf # change those names to fit your needs
          
      - name: "Release"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest" # Realease will be tagged latest and old one will be removed
          prerelease: false
          title: "Current Notes" # Name of the release
          files: |
            *.pdf # only keep the pdf files
